### PR TITLE
Solution 3

### PR DESCRIPTION
**Pull request by ellu-laitinen**
I made my own version of the clicker app

### CODE REVIEW

**Comment by ellu-laitinen** [comment]
@codeclassifiers, can you check my pull request? Also, it says on my hacktober profile page that this repository is an ineligible repository and not participating in hacktoberfest. I noticed in the About section the label says hacktobefest, so there's a tiny typo there, maybe that's causing the issue.

**Comment by saurabhnative** [comment]
@ellu-laitinen I have fixed typo in repo details as requested in previous comment and also adding relevant labels to this PR as per official Hacktoberfest guidelines. Thank you for your contributions to this repository.

**Comment by codeclassifiers** [comment]
@all-contributors please add @ellu-laitinen  for adding solution_3 in this repository

**Comment by saurabhnative** [comment]
@all-contributors please add @ellu-laitinen for adding code for solution_3 in this repository

**Pull request merged**
